### ISSUE TITLE
Bump the cli/sdk version to 0.1.0.40311654 in shrike and its documentation

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#107]

**Comment by dkmiller** [comment]
https://teams.microsoft.com/l/message/19:ad330b8316204faf8ea3bca2219fe011@thread.tacv2/1624867741460?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=96fec103-1096-4e58-9ac4-d3fc32308972&parentMessageId=1624604818421&teamName=AML%20Designer%2FPipeline%20Forum&channelName=Custom%20Module&createdTime=1624867741460
