### ISSUE TITLE
Minimal in-repo pipeline example

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#113]
**Category**

- [x] shrike.pipeline
- [ ] shrike.build
- [ ] shrike.compliant_logging

**Is your feature request related to a problem? Please describe.**

Potential users who are not doing compliant experimentation may want to use the "pipeline" part of this library.

**Describe the solution you'd like**

Simple examples of using this library for pipeline configuration and submission, that are not "tied" to compliance. Something like the logging examples.

**Describe alternatives you've considered**

One option: rely on the compliance-focused accelerator repo. This will not help non-compliant customers.

**Estimate the Impact**

This would make it much easier for WebXT to use the library.

@jfomhover FYI.

**Comment by thomasp-ms** [comment]
@dkmiller @jfomhover this is aligned with the problem set I'm working on, so I'm assigning this to myself. I will add on example in this repo. I should be able to complete by EOW.

**Comment by dkmiller** [comment]
Hey @thomasp-ms ,

@jfomhover has some WebXT-related LightGBM pipeline that could help as reference example here.

**Comment by dkmiller** [comment]
Just spoke with Jeff about this.

He'll contribute a public-facing LightGBM pipeline. There are some open questions on _where_ it should go (and how it should integrate with the build pipeline(s)), but the main code should be straightforward.

**Comment by fuhuifang** [comment]
> Just spoke with Jeff about this.
> 
> He'll contribute a public-facing LightGBM pipeline. There are some open questions on _where_ it should go (and how it should integrate with the build pipeline(s)), but the main code should be straightforward.

How about an "example" folder here? We need some illustration of how shrike works anyway, and we don't have to share both this repo + acc repo when non RingX people ask for an example.
