### ISSUE TITLE
Spelling error -  Valiad experiment ...

### ISSUE THREAD

**Issue by pegulhane** [Azure/shrike#121]
**Before filing, make sure to upgrade to the latest shrike version and check if the bug reproduces.**

**Category**
Please select:
- [x] shrike.pipeline
- [ ] shrike.build
- [ ] shrike.compliant_logging

Please also add corresponding labels.

**Describe the bug**
Spelling mistake 
Traceback (most recent call last):
  File "\shrike\pipeline\pipeline_helper.py", line 987, in hydra_run
    main_instance.run()
  File "\shrike\pipeline\pipeline_helper.py", line 851, in run
    self.validate_experiment_name(self.config.run.experiment_name)
  File "shrike\pipeline\pipeline_helper.py", line 175, in validate_experiment_name
    raise ValueError(
ValueError: **Valiad** experiment names must only contain letters, numbers, underscore and dash!

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version info**
Which version of shrike are you using?

**Additional context**

**Comment by haozhestat** [comment]
@pegulhane : Thank you so much for sharing the spelling error in the shrike.

@fuhuifang : Could you create a PR to change it from "Valiad" to "A valid"? https://github.com/Azure/shrike/blob/2d02cabb07edc40b424f8c40b4760e8601900bcd/shrike/pipeline/pipeline_helper.py#L181
