### ISSUE TITLE
Design for how shrike can shield users from breaking changes between component and vNext SDKs

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#124]
**Category**

- [x] shrike.pipeline
- [x] shrike.build
- [x] shrike.compliant_logging

**Is your feature request related to a problem? Please describe.**

Azure ML is planning to release the "vNext" of their Python SDK. Shrike can help shield users from potential breaking changes between the component SDK and vNext.

**Describe the solution you'd like**

A precise technical design \& plan for how shrike can shield users from breaking changes between component and vNext SDKs.

**Describe alternatives you've considered**

Force users to migrate. This will be painful.

**Estimate the Impact**

1. All Office and WebXT data scientists will benefit.
2. From the module &mapsto; component SDK migration, estimate this will save &gt; 2 weeks / team.

**Additional context**

See the [vNext pipelines DSL spec](https://github.com/Azure/azureml_run_specification/blob/master/specs/dsl.md).

**Comment by dkmiller** [comment]
@haozhestat let's use this to track design work.

**Comment by haozhestat** [comment]
@dkmiller : Should we close this issue as the following doc is ready for review now?

[2021.06.30-shrike-1.5-vnext-migration.docx](https://microsoft.sharepoint.com/:w:/t/AMLDataScience/EViICiHoVE1AmwvA-h1mVi4BNZtN-ydp73su6O8fa355vw?e=SxeCNN)

**Comment by dkmiller** [comment]
@haozhestat let's wait until it's been more broadly shared
