### ISSUE TITLE
Tags for copied files are not added appropriately / No reasonable error message

### ISSUE THREAD

**Issue by felixnext** [Azure/shrike#132]
**Before filing, make sure to upgrade to the latest shrike version and check if the bug reproduces.**

**Category**
Please select:
- [ ] shrike.pipeline
- [x] shrike.build
- [ ] shrike.compliant_logging

Please also add corresponding labels.

**Describe the bug**

When using the following prepare step:
```
- task: AzureCLI@2
  displayName: 'Validate AML Modules (prepare)'
  inputs:
    azureSubscription: 'CONNECTION'
    scriptLocation: inlineScript
    scriptType: pscore
    inlineScript: |
      python -m shrike.build.commands.prepare --configuration-file $(ROOT_DIR)/build/config/convrel-config.yaml
    workingDirectory: $(ROOT_DIR)/$(BUILD_DIR)
```

with `suppress_adding_repo_pr_tags` set to `False` the pipeline will fail if the regarding work files are not originally checked in to Git, but rather copied.
(Use case: We create an adhoc deploy folder and copy all dependencies there)

This failes with the following error:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\shrike\build\commands\prepare.py", line 846, in <module>
    Prepare().run()
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\shrike\build\core\command_line.py", line 319, in run
    self.run_with_config()
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\shrike\build\commands\prepare.py", line 706, in run_with_config
    component_files = self.add_repo_and_last_pr_to_tags(component_files)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\shrike\build\commands\prepare.py", line 228, in add_repo_and_last_pr_to_tags
    last_commit = next(repo.iter_commits(paths=file, max_count=1))
StopIteration
```

**To Reproduce**

> See above

**Expected behavior**

Ideally the `StopIteration` error should be caught and a warning given that the tag could not be added (alternatively, add a strict mode that allows to fail at this step with a meaningful error)

**Best Case**: Since this will also break smart mode (I assume), this will only work anyway when `all` deployment mode is selected. From that perspective it would be nice to just leverage the general information from the Git Repo instead of single file to figure out the PR - i.e. make the logic work with copied files as well.

**Version info**
Which version of shrike are you using?

1.8.0

**Additional context**

**Comment by dkmiller** [comment]
Adding [internal link with context](https://stackoverflow.microsoft.com/questions/267090) for posterity.

**Comment by dkmiller** [comment]
@felixnext quick question. If your component files aren't in Git, shouldn't you be setting

```yaml
suppress_adding_repo_pr_tags: true
```

I see what looks like the correct logic [in prepare.py](https://github.com/Azure/shrike/blob/75b5b0e0d30c7d4e78b4fab138b09701037331c4/shrike/build/commands/prepare.py#L705).

I agree that in any case, the thrown exception should be more clear.
