### ISSUE TITLE
Shrike's preparation logic should generate environment.yml file for Conda-native dependencies

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#162]
**Category**

- [ ] shrike.pipeline
- [x] shrike.build
- [ ] shrike.compliant_logging

**Is your feature request related to a problem? Please describe.**

> **⚠️ It is not entirely clear yet whether this is needed. Don't proceed to implementation until that is settled.**

Office is creating a process for data scientists to use Conda-"native" dependencies in their environment files. Sadly, component governance doesn't pick up those kind of dependencies by default.

**Describe the solution you'd like**

This library should create a [cgmanifest.json](https://docs.opensource.microsoft.com/tools/cg/features/cgmanifest/) file for the Conda-native dependencies in a component's environment.

**Describe alternatives you've considered**

No alternatives, we'll have to do this.

**Estimate the Impact**

1. All Office data science teams.
2. Compliance risk.

**Additional context**

Waiting on Matt McKenzie to share additional details on what content needs to go into the cgmanifest file.

**Comment by dkmiller** [comment]
Another option, generate `environment.yml` files to be picked up by @mmckenz logic https://github.com/microsoft/componentdetection-bcde/pull/346/files

**Comment by haozhestat** [comment]
I confirmed with @mmckenz and @dkmiller today. The solution is to **put Conda deps in environment.yml and put pip deps in requirements.txt**.
