### ISSUE TITLE
Higher numpy dependency

### ISSUE THREAD

**Issue by lynochka** [Azure/shrike#166]
Hei,
shrike[build,dev,pipeline] 1.9.4 depends on numpy==1.19.3; extra == "dev", while I am sure many of the ML teams require numpy >=1.20.1.
Could this be loosened?

**Comment by romanwerpachowski** [comment]
Numpy 1.19.3 does not have type stubs, which breaks mypy type checks.

**Comment by lynochka** [comment]
Sorry, I noticed that a teammate added [dev] to extras in the requirements, removing it helped keeping newer dependencies.

**Comment by dkmiller** [comment]
In general, we discourage installing `dev` in production environments &mdash; that extra "pins" many Python dependencies to keep the shrike build deterministic.

The production extras (`build`, `pipeline`) do not pin numpy.
