### ISSUE TITLE
Support customized parameters for "subgraph"

### ISSUE THREAD

**Issue by AliMahmoudzadeh** [Azure/shrike#170]
Current implementation forces subgraphs to use the same config as the pipeline.  This prevents users to call variations of the same subgraph with build-time conditionals. The functionality was previously worked on by Multimedia team. You can check the implementation [here](https://msasg.visualstudio.com/Bing%20Image%20Index/_git/ImageRankerAML?path=%2Fpipelines%2Futil%2Fpipeline_helper.py).

**Comment by dkmiller** [comment]
Hi @alimahmoudzadeh , can you add some more detail? How did your implementation enable subgraphs to use their own configs (both on implementation and consumption side)?

**Comment by AliMahmoudzadeh** [comment]
@dkmiller, I added a PR for this feature https://github.com/Azure/shrike/pull/172
