### ISSUE TITLE
Programmatically setting the run display name

### ISSUE THREAD

**Issue by shatu** [Azure/shrike#183]
Now that the support for setting the run display-name has been released in AML, can we add the support for setting it through shrike as well? https://stackoverflow.microsoft.com/questions/273990

I tried simply passing `display_name` to the run object through the config, and the pipeline build failed.
![image](https://user-images.githubusercontent.com/892650/132926856-671203c7-f413-4f75-91fa-3ce5209c155b.png)

**Comment by haozhestat** [comment]
Thanks for the feature request, @shatu .

`display_name` will be supported in the component SDK in the upcoming release (target date: 2021-09-30).

We will support `display_name` in the shrike once this new version of component SDK is released.

![image](https://user-images.githubusercontent.com/18077361/133008334-5b5e8235-2b91-4f26-ac2f-625e4a2386ca.png)

cc: @dkmiller

**Comment by jfomhover** [comment]
One thing I have conflicting thoughts about, and you might want to watch out: if you use the run.display_name approach, all your runs will have the same name unless you modify it everytime you re-run your pipeline. It will make your run history hard to browse.

It might be better just to let users use dsl.pipeline(display_name="") on their own to avoid setting our own naming standards (that would be redundant with AzureML "naming" conventions)

**Comment by nifarn** [comment]
Is there a way to re-use the same two word random display name generator currently used by AML? If not, could it be exposed through shrike? While doing something like `dsl.pipeline(display_name=f"cool-pipeline-{datetime.now()}", ...)` certainly is good enough to create unique titles, I personally find a name like `cool-pipeline-busy_nutmeg_xynw6ly3` far easier to remember than `cool-pipeline-2021-10-29 11:44:43.028129`.

**Comment by dkmiller** [comment]
@nifarn you can't reuse the _exact_ two-word random generator, but Python provides some nice libraries, e.g. [coolname](https://pypi.org/project/coolname/).

E.g.

```python
from azure.ml.component import dsl
from coolname import generate_slug

@dsl.pipeline(display_name=f"cool-pipeline-{generate_slug(2)}")
def pipeline():
    ...
```

**Comment by haozhestat** [comment]
@shatu, your proposed feature (shown below) is supported now. Feel free to install the latest version of shrike and give it a try.

![image](https://user-images.githubusercontent.com/18077361/140242655-3559f63a-16e9-4f95-b4a3-ea88b94b7932.png)
