### ISSUE TITLE
Increase the coverage rate of shrike.pipeline

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#19]

**Comment by haozhestat** [comment]
@fuhuifang : We need to add unit tests for the following 7 functions in the `pipeline_helper.py`. I just made the assignment. Does it look good to you?

Assigned to Haozhe:
- [ ] _apply_windows_runsettings
- [ ] _apply_hdi_runsettings
- [ ] _apply_linux_runsettings
- [ ] apply_recommended_runsettings
- [ ] _parse_pipeline_tags

Assigned to Fuhui:
- [ ] _apply_scope_runsettings
- [ ] _apply_datatransfer_runsettings

**Comment by fuhuifang** [comment]
Can we close this issue now?

**Comment by haozhestat** [comment]
@dkmiller and @fuhuifang : 

The overall coverage rate of shrike has reached 81\%, higher than the threshold 80\% we set before, after completing the following three pull requests which adds unit tests to pipeline_helper.

- #82 
- #78
- #79

**Comment by dkmiller** [comment]
@haozhestat , this is great!

Can you make the new coverage threshhold (80%) mandatory?

**Comment by haozhestat** [comment]
@dkmiller : Technically, I don't know how to make the overall threshold mandatory, because we do the unit tests for pipeline, build and compliant_logging separately. 

But I could have three different threshold for three parts.

**Comment by dkmiller** [comment]
@haozhestat yes, let's have three threshholds for the three parts.

**Comment by haozhestat** [comment]
@dkmiller : Just created an issue for your request

https://github.com/Azure/shrike/issues/85
