### ISSUE TITLE
metapackage dependency

### ISSUE THREAD

**Issue by vizhur** [Azure/shrike#235]
please replace dependency on a metapackage azureml-pipeline~=1.35.0 with real dependencies you need from AzureML Python SDK

**Comment by haozhestat** [comment]
@vizhur : The `azureml-pipeline` package is directly imported and used in the `shrike.pipeline.pipeline_helper`. 

https://github.com/Azure/shrike/blob/be7c1dbcc11d7fac1ded760b7c64697b80ae86cb/shrike/pipeline/pipeline_helper.py#L30

Could you elaborate more on your request?

**Comment by haozhestat** [comment]
@vizhur : Do you mean replacing `azureml-pipeline` by `azureml-pipeline-core`?

**Comment by vizhur** [comment]
yes, pipeline core or steps, the actual dependency you need. azureml-pipeline is a metapackage package with no code

**Comment by haozhestat** [comment]
@vizhur : Sure. I just updated it in the PR #236.
