### ISSUE TITLE
"Strict" validation logic in the "shrike.build.prepare"

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#36]
This feature request comes from a brainstorm meeting among @dkmiller, @haozhestat, @felixnext and @iladan on 5/20/2021.

Examples of "strict" validation logic:
- auto-inject link to component codebase into the description
- allow configurable validation logic on component descriptions
- require email address in component description
- force all parameters to have "proper" descriptions
- enforce naming conventions (e.g., office.*.(compute))
- compliance validation "up front" (e.g., verify image name, verify Conda environment)

The python script used by conversational relevance team to verify modules:
- [script-verify-module-docs.py - Repos (visualstudio.com)](https://eemo.visualstudio.com/TEE/_git/TEEGit?path=%2FOffline%2FConversationalRelevance%2Fscripts%2Fscript-verify-module-docs.py&version=GBdevelop&_a=contents)
- [step-verify-module-docs.yaml - Repos (visualstudio.com)](https://eemo.visualstudio.com/TEE/_git/TEEGit?path=%2FOffline%2FConversationalRelevance%2Fops%2Fstep-verify-module-docs.yaml&version=GBdevelop&_a=contents)

**Comment by haozhestat** [comment]
@haozhestat will write a proposal (RFC) after AML FHL (i.e, after 6/1).

**Comment by haozhestat** [comment]
The aml modules validation file in the smartcompose repo might be a good example:

[Offline/SmartCompose/src/python/tests/aml/test_aml_modules.py](https://eemo.visualstudio.com/TEE/_git/TEEGit?version=GBdevelop&path=%2FOffline%2FSmartCompose%2Fsrc%2Fpython%2Ftests%2Faml%2Ftest_aml_modules.py)

**Comment by dkmiller** [comment]
See this (internal) link: https://msdata.visualstudio.com/Vienna/_workitems/edit/1204658 .

Also worth having this "strict" mode on pipeline _submission_ time (for local component definitions).

**Comment by haozhestat** [comment]
@dkmiller and @felixnext : I have created a draft proposal for "Strict" validation logic in the "shrike.build.prepare"

[Pull Request 602450: Proposal for "Strict" Validation of AML Components](https://dev.azure.com/msdata/Vienna/_git/aml-ds-internal/pullrequest/602450)

**Comment by haozhestat** [comment]
@dkmiller and @felixnext : #109 is the new proposal based on jsonpath expression and regular expression.
