### ISSUE TITLE
Testing shrike in the HDI and PolymerPackages feed using Search Relevance pipeline

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#49]

**Comment by fuhuifang** [comment]
1. [converted repo](https://eemo.visualstudio.com/TEE/_git/TEEGit/pullrequest/22068?path=%2FOffline%2FSearchRelevance%2Fops%2Ftemplate-conda-env.yaml)
2. [successful submission](https://ml.azure.com/runs/987f9091-c667-4c81-a737-0ab56d094177?wsid=/subscriptions/60d27411-7736-4355-ac95-ac033929fe9d/resourcegroups/MOP.HERON.PROD.a9221f3e-d7d8-493c-bc83-3083409e31f8/workspaces/amlworkspaceeakrxgox3vang&tid=cdc5aeea-15c5-4db6-b079-fcadd2505dc2)
3. [Azure DevOps build](https://eemo.visualstudio.com/TEE/_build/results?buildId=826662&view=logs&j=e24aea9e-642d-565f-0ea4-ee7a5a3b8fdc)
