### ISSUE TITLE
This library should produce a "transient" requirements file containing all Python dependencies in components

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#83]
It should, for _each_ component specification file,

- Parse the relevant Conda environment (YML or YAML) file
    - Make sure to handle `conda_dependencies` (inline), `conda_dependencies_file`, `pip_requirements_file`.
    - Refer to command component schema: https://componentsdk.blob.core.windows.net/jsonschema/CommandComponent.json .
- Extract out the list of Python package dependencies
- Append those to some interna list
- (at end of "prepare" step) dump the complete list of a single **requirements.txt** file in a "dummy" directory in root of repo (root / GUID / file )

Helpful clarification: Component Governance _already_ chases down transitive dependencies!

Also,

> Document that users **must** run component governance as part of their build, _after_ the prepare step.

Consider detecting "whether" (boolean) CG has run and _log that info_ to app insights.

----

Other approach, only specify component dependencies via `requirements.txt` files (don't do this).

----

Tentative ETA: 6/25.

**Comment by fuhuifang** [comment]
How do we handle "conflicting" requirements? Removing the version number? Here's the file generated when running this new command against acc repo:

pandas==1.1.5
pandas==1.1.5
**azureml-defaults**
azureml-core==1.20.0
tensorboard==2.4.0
**azureml-defaults==1.20.0**
azureml-telemetry==1.20.0
**azureml-defaults==1.13.0**
transformers==3.5.1
azureml-core==1.27.0
torch==1.6.0
matplotlib
scikit-learn==0.23.2
shrike
numpy==1.19.4
azureml-core==1.20.0
tensorboard==2.4.0
**azureml-defaults==1.20.0**
azureml-telemetry==1.20.0
**azureml-defaults==1.13.0**
transformers==3.5.1
azureml-core==1.27.0
torch==1.6.0
matplotlib
scikit-learn==0.23.2
shrike
numpy==1.19.4

**Comment by haozhestat** [comment]
@fuhuifang : Thanks for taking this workitem!

- I think the generated requirement files are component-specific, so there should not be "conflicting" packages.
- The generated requirement files will be auto-detected and consumed by the "Component Governance" Task right after the "prepare" step.

**Comment by dkmiller** [comment]
I agree with @haozhestat , suggest a folder structure like:

```
repo_root/
  component_depencies_((guid))/
    component_name_1/
      requirements.txt
    component_name_2/
      requirements.txt
    ...
```

That way, the CG alerts will clearly display _which_ component had the dependency.

**Comment by haozhestat** [comment]
@fuhuifang : If you don't have a good idea of the **guid**, you may consider using "datetime". 

```
repo_root/
  component_dependencies_(datetime)/
    component_name_1/
      requirements.txt
    component_name_2/
      requirements.txt
    ...
```
