### ISSUE TITLE
This library contains an implicit dependency on pytest

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#87]
There's testing code with dependencies on pytest and ruamel inside the "main" lib:

https://github.com/Azure/shrike/blob/main/shrike/pipeline/testing/components.py

This causes certain imports to fail after a fresh install.

E.g.,

```
docker run -it python:3.7 /bin/bash
pip install shrike[pipeline]
python
from shrike.pipeline.testing.components import component_run_py_import, component_spec_yaml_exists_and_is_parsable
```

I think the code under `pipeline/testing/components` should be moved to a top-level "tests" namespace which is _not_ included in the package.

**Comment by haozhestat** [comment]
@fuhuifang and @dkmiller : 

- The `pipeline` part of `shrike` is mainly used in the local environment. Data scientists usually do unit tests or run some local dummy pipelines in their local environments before submitting a remote run. So it is OK for me to adding extra dependencies (such as pytest related packages) into  the `requirements/requirements-pipeline.txt` file.
-  The code under `pipeline/testing/components` are the utilities functions for AML integration tests, widely adopted by customers, such as smart compose and search relevance. We should not move them into the "tests" namespace.

**Comment by dkmiller** [comment]
@haozhestat , this makes sense to me. Go ahead and add the necessary dependencies into the pipeline-specific requirements.

**Comment by fuhuifang** [comment]
> @fuhuifang and @dkmiller :
> 
> * The `pipeline` part of `shrike` is mainly used in the local environment. Data scientists usually do unit tests or run some local dummy pipelines in their local environments before submitting a remote run. So it is OK for me to adding extra dependencies (such as pytest related packages) into  the `requirements/requirements-pipeline.txt` file.
> * The code under `pipeline/testing/components` are the utilities functions for AML integration tests, widely adopted by customers, such as smart compose and search relevance. We should not move them into the "tests" namespace.

Agreed! I'll create a PR this afternoon.
