### ISSUE TITLE
Adopt shrike and deprecate old tooling packages in the Canary pipeline

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#92]
In the [canary pipeline](https://dev.azure.com/msdata/Vienna/_git/aml-ds?path=%2Frecipes%2Fcanaries%2Fpipelines%2Fprs.py), the old tooling packages (e.g., `aml-ds-pipeline-contrib` and `confidential-ml-utils`) are still being used. Let's completely adopt shrike in the aml-ds repo.

**Comment by dkmiller** [comment]
@ShizeSu06 is planning on picking up this work.

**Comment by haozhestat** [comment]
https://dev.azure.com/msdata/Vienna/_git/aml-ds/pullrequest/623918
