### ISSUE TITLE
Add functionality to provide dependency "hints" to the build tooling

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#94]
Meta-point: this issue is for **discussion first**. Not clear if we want to / should implement the functionality being discussed below.

----

Use case suggested by @felixnext .

Some teams have complicated build pipelines which, e.g., build C\# code, copy in binary dependencies, and "wrap" everything in a .zip file which is copied into the component snapshots by a single PowerShell file. All this means that the "smart" mode is useless in such a build, since changes in the `.zip` file are not visible in the Git history of the underlying repo.

How to improve that experience? A couple ideas (non-exclusive &mdash; we could implement both).

1. Per-component dependency hints _a la_ additional include files, e.g. `spec.dependency_hint`. This could specify a list of paths / globs which shrike treats as dependencies in smart mode but are not explicitly copied around.
    - Users could either manually write those dependency hints or programmatically generate them as part of the build + copy logic.
    - Pro: similar "look and feel" to additional includes.
    - Con: potential for boilerplate just like additional includes
2. Global configuration of dependency hints, e.g. a field `dependency_hints` in the build configuration file which maps component names to glob and/or list of globs. Something like the example below.
    - Pro: less boilerplate.
    - Con: may be confusing / hard to maintain?

```yaml
dependency_hints:
- '*.hdi.*': ../large_dependency_folder/**
- '*.gpu.*': [ folder_1/*.py , folder_2/*.so ]
```

**Comment by haozhestat** [comment]
@felixnext : Would you mind leaving a comment on value-add of dependency "hint" functionality. We had a shrike backlog review meeting today to determine the priority levels of shrike workitems. You inputs will be extremely helpful.

cc: @dkmiller

**Comment by haozhestat** [comment]
Comment from @danrsc on this issue: we shouldn't implement this. We don't want lots of "bespoke" ADO pipelines.

**Comment by felixnext** [comment]
This would be a very welcome feature for us. Currently smart mode is not usable for us, due to two reasons:

1. Lots of zip dependencies (for Spark Modules) which are not tracked appropriately
2. The `.additional_dependencies` for us use paths relative to the root of the repo (to make them easier to read for us, as `../..` style paths are prone to errors)

Would be great if there would be a way to improve both of this through dependency hints (Also would be great if we could specify in the config to which folder smart mode should make the `additional_includes` and `dependency_hints` files relative to. I guess this can also be done in the global file?).

I would also be happy to help out on this feature.

**Comment by felixnext** [comment]
I also would not agree of the "bespoke" comment, as this does not really change the ADO pipeline, but only the dependencies that are pulled in for smart mode. (@danrsc maybe I am misunderstanding the comment here?)

**Comment by andrea8moro** [comment]
I dont see this as bespoke too. each time I do a change to a shared library I need to change something in each component to force their republishing

**Comment by dkmiller** [comment]
@felixnext , @andrea8moro &mdash; thanks for adding your thoughts. We'll keep this in mind in the next cycle of planning.

**Comment by felixnext** [comment]
The tags indicate that this is shipped in Q2, is there an update on availability?

**Comment by dkmiller** [comment]
Hi @felixnext , this will slip slightly into Q3 (Jan&ndash;March) but not by much. It should land within the first couple weeks of the new year.

**Comment by dkmiller** [comment]
@haozhestat , good suggestion from @felixnext is to write some basic docs for this functionality; otherwise people have to read the implementation.
