### ISSUE TITLE
Smart logic fails when compliant branch is of regex-style

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#95]
Mingzhu Yuan reported the following error message when she ran the SmartAction signing/registering build in the smart mode with `config.compliant_branch = ^refs/heads/(develop|compliant/.*)$`

- Build link: https://eemo.visualstudio.com/TEE/_build/results?buildId=843826&view=logs&j=e24aea9e-642d-565f-0ea4-ee7a5a3b8fdc&t=5f7e3870-71f5-5ccb-156e-26d7a9a1cfab

```
File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\shrike\build\commands\prepare.py", line 395, in get_modified_files
compliant_branch
File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\git\util.py", line 979, in __getitem__
raise IndexError("No item found with id %r" % (self._prefix + index)) from e
IndexError: No item found with id 'origin/(develop|compliant/.*)'
```

**Comment by thomasp-ms** [comment]
This is expected - code isn't written to handle regexes. Maybe let's discuss during next sync whether we want to support this? @haozhestat do you know what Mingzhu is trying to achieve? (to see if we can provide a quick workaround in the mean time; a quick and dirty one one would be to have one branch per build config file, then several prepare/register stages in the build, although I'm not sure it wouldn't lead to other issues)

**Comment by haozhestat** [comment]
The [default value](https://github.com/Azure/shrike/blob/308c2566753470239136c54406969f4762fa2537/shrike/build/core/configuration.py#L20) of `config.compliant_branch` is `^refs/heads/main$` rather than `refs/heads/main`. It may have delivered a misleading message that the `compliant_branch` parameter should be written as a regular expression.

@thomasp-ms : Thanks for sharing your insights here. I will be OOF for a week from Monday. Could you follow up with Mingzhu Yuan and ask more context from her?
- If she is OK with the proposed quick workaround, please feel free to close this issue;
- elif she really needs the regex support, let's have a discussion on the next steps in the scrum meeting. 

cc: @dkmiller and @fuhuifang

**Comment by thomasp-ms** [comment]
I see. I also noticed in the documentation we wrote "_Another way of achieving similar functionality is to run a "smart mode" build which triggers against all compliant/* branches._", which is even more misleading. I'll fix this and follow up with Mingzhu.

**Comment by haozhestat** [comment]
Closing this issue after following up with Mingzhu. She has been unblocked.
