### ISSUE TITLE
`shrike.pipeline.testing.find_run_py_in_command()` cannot find the run.py script in the additional_includes

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#97]
This is an issue reported by Mingzhu Yuan.

For common scenarios, the `run.py` script is located in the same folder as the component spec yaml file. However, in the spark.net component of search relevance project, the `run.py` is located in the different folder specified in the additional_includes. Below is how the additional_includes file looks like:
```
../../spark.net/run.py
../../packages/smartaction-common-lib.zip
../../packages/consumption-1.0-SNAPSHOT.jar
../../packages/microsoft-spark-2-4_2.11-1.0.0.jar
../../packages/SparkNetTEEDecoder.zip
```

When the `run.py` script is not in the same folder as the component spec yaml, the `shrike.pipeline.testing.find_run_py_in_command()` will fail in the integration tests. Below is an example of the error message:

```
def component_run_py_import(component_spec_path):
"""Try importing run.py, just to check if basic script passes syntax/imports checks"""
definition, use_component_sdk = component_spec_yaml_exists_and_is_parsable(
component_spec_path
)

run_py_command, definition_command = find_run_py_in_command(
definition, use_component_sdk
)

component_import_path = os.path.dirname(component_spec_path)
run_py_absdir = os.path.join(component_import_path, run_py_command)
assert os.path.isfile(
run_py_absdir
), "Component {} has command {} using a python script {} that cannot be found".format(
> component_spec_path, definition_command, run_py_command
)
E AssertionError: Component D:\src\TEEGit\Offline\SmartAction\python\src\steps\spark-net-tee-decoder\module_spec.yaml has command --AppName {inputs.app_name} --AppGuid {inputs.app_guid} --ZipFile SparkNetTEEDecoder.zip --BinaryName SparkNetTEEDecoder [--Input_ModelPath {inputs.input_model_path}] --Input_DataPath {inputs.input_data_path} --Output_EncryptedOutput {outputs.output_encrypted_output} --Output_EncryptedScore {outputs.output_encrypted_score} --Output_UnEncryptedStat {outputs.output_unencrypted_stat} --Program {inputs.program} --WorkflowParser {inputs.workflow_parser} --Entities {inputs.entities} [--ScoreAggStrategyForArray {inputs.score_agg_strategy_for_array}] --ModelName {inputs.model_name} [--DependencyModelName {inputs.dependency_model_name}] --DependencyPath {inputs.dependency_path} --DecodeColumnName {inputs.decode_column_name} [--OutputColumn {inputs.output_column}] [--ExternalInputColumnName {inputs.external_input_column_name}] --LabelColumnName {inputs.label_column_name} --InputFormat {inputs.input_format} [--InputHeader {inputs.input_header}] [--OutputFormat {inputs.output_format}] [--OutputHeader {inputs.output_header}] [--Debug {inputs.debug}] [--Persist {inputs.persist}] [--Repartition {inputs.repartition}] using a python script run.py that cannot be found
D:\ProgramData\Anaconda3\envs\searchrelevance\lib\site-packages\amldspipelinecontrib\testing\components.py:280: AssertionError
```

**Comment by fuhuifang** [comment]
If we just search for `run.py` in component folder + additional includes, my concern is that there might be multiple `run.py`. 

We could also make an exception for Spark.Net, as `run.py` is the same for all Spark.Net components. If the component is detected as Spark.Net, we can copy `run.py` over to component folder.

**Comment by thomasp-ms** [comment]
Here are my 2 cents.
- That use case seems legitimate, and I imagine other teams might follow that pattern eventually, maybe for other types of components too; or some teams might NOT follow this pattern for their spark.net components; this would make maintaining some sort of hard-coded rules quite painful.
- I believe the concern raised by @fuhuifang about searching in component_folder + additional_includes is valid; one way to mitigate it could be to instruct teams, if they want to follow such a pattern of a shared run.py, to explicitly list it in additional_includes (so we can just grab it directly, without the risk of not knowing which one to use if several are present). Not ideal either since it requires communicating this explicitly, but it might be better than the other approaches.

I do not have full context on this though, so please take my comment with a grain of salt. I think it's worth discussing in a sync.

**Comment by haozhestat** [comment]
@fuhuifang and @thomasp-ms : Thanks for your insightful comments. They make sense.

> If we just search for run.py in component folder + additional includes, my concern is that there might be multiple run.py.

By the way, I am a bit confused about the multiple `run.py` scripts. The `shrike.pipeline.testing.find_run_py_in_command()` function will only be used in the unit tests (more specifically, aml integration tests). If the users specify the path of `run.py` in the `.additional_includes` then the `run.py` should not be in the directory of component spec YAML file.

**Comment by thomasp-ms** [comment]
@haozhestat yes, there shouldn't be another `run.py` the directory of the component spec, but there could potentially be one in another directory that ends up being pulled by the `additional_includes` if the users casts too wide a net with that file. At least that was my interpretation of @fuhuifang 's concern

**Comment by haozhestat** [comment]
Got it. I had a phone call with @fuhuifang . Let's close this issue. Feel free to re-open it if any other customers experience the same error.
