### ISSUE TITLE
Adding "everything but few modules" for "use_local" option on configs for shrike.pipeline

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#98]
This is a feature request from Kunho Kim (@kunho):

> Recently I wanted to execute a pipeline with using all local version for each module but the data transfer (which requires a signed build),
> To be able to do that, I changed the pipeline’s config file under module_loader like below:
> 
> module_loader:
>     use_local: “ConvertGleanData,TrainModel,GetTrainedEmbeddings”
> 
> This example only needed to list 3 modules there to achieve this, but if we imagine we want to do this for a pipeline that has large number (50+) of modules, it would be inconvenient to list all of the modules. Ideally, if there is some option that we can set “all but few modules” it would be easier for us to use. 
> 
> Especially this feature would be useful on unit tests for pipeline validation – which we would like to use the local version of modules to check if the pipeline passes the validation.
> Please let me know if you need more explanations, happy to also discuss offline.

**Comment by fuhuifang** [comment]
My thought: adding a `use_remote` config

**Comment by haozhestat** [comment]
@fuhuifang : I like your idea on adding a `use_remote` config. It can address this feature request. However, we may have to address the conflicts between `use_local` and `use_remote` when `use_local + use_remote != All Components` or `the intersection of use_local and use_remote is not None`.

I have an alternative proposal: use a special symbol (e.g., braces) to imply ** exclusion** in the `use_local`. For instance,
- `use_local: "*"` means using the local version of all components
- `use_local: "component_1,component_2"` means using the local version of component_1 and component_2
- `use_local:"(component_1), (component_2)"` means using the local version of all components except component_1 and component_2

@fuhuifang : Hope to hear your comments.

**Comment by fuhuifang** [comment]
Yes I agree with you. We may also use "minus": `use_local:"-component_1, -component_2"`. Need to investigate further on allowed characters in component key. I'll draft a PR next Monday.

**Comment by haozhestat** [comment]
@fuhuifang : You could find the allowed charaters from the [CommandCommand schema](https://componentsdk.blob.core.windows.net/jsonschema/CommandComponent.json). 

From the schema, we find that the component name match `"^[A-Za-z0-9-_.]+$"`, so the `dash` symbol (i.e., "minus") is allowed in the name.

![image](https://user-images.githubusercontent.com/18077361/122611819-d711a000-d036-11eb-8efc-fc29618f9e6c.png)

**Comment by fuhuifang** [comment]
How about "~"? I just want something indicating "not" 😄

**Comment by haozhestat** [comment]
"~' looks good to me.

**Comment by kunhokim127** [comment]
The suggestion looks good to me, thanks for your quick responses!
